name: Bot Deployment

on:
  push:
    branches:
      - main  # Change this to the branch name you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # Change this to the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Change this to the path of your requirements file

      - name: Run the bot
        run: python bot.py  # Change this to the filename of your bot script
